## Numpy array and basics

In [1]:
import numpy as np

## Creating Array from Lists

In [3]:
array_1d=np.array([1,2,3,4,5,6])
print("1d array: ",array_1d)
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print("2d array: ",array_2d)



1d array:  [1 2 3 4 5 6]
2d array:  [[1 2 3 4]
 [5 6 7 8]]


## List vs Numpy array

In [11]:
py_list=[1,2,3,4,5]
print("Multiplication of list",py_list*2)
numpy_array=np.array([1,2,3,4,5])
print("Multiplication of numpy array",numpy_array*2)

import time
start=time.time()
py_list1=[i*2 for i in range(1000000)]
print("Time taken for list",time.time()-start)
start1=time.time()
numpy_array1=np.arange(1000000)
print("Time taken for numpy array",time.time()-start1)
# start2=time.time()
# numpy_array2=np.array([i*2 for i in range(1000000)])
# print("Time taken for numpy array2",time.time()-start1)



Multiplication of list [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Multiplication of numpy array [ 2  4  6  8 10]
Time taken for list 0.10463380813598633
Time taken for numpy array 0.003025054931640625


## Creating array from scratch

In [13]:
zero=np.zeros((4,5))
print("Zero matrix: ",zero)
one=np.ones((3,3))
print("Matrix of ones: ",one)
constant=np.full((3,3),8)
print("Matrix of constants: ",constant)
random=np.random.random((2,3))
print("Matrix of randoms: ",random)
sequence=np.arange(2,10,2)
print("Sequence matrix: ",sequence)





Zero matrix:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matrix of ones:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix of constants:  [[8 8 8]
 [8 8 8]
 [8 8 8]]
Matrix of randoms:  [[0.61093177 0.77449681 0.4816446 ]
 [0.69370662 0.93157963 0.61958462]]
Sequence matrix:  [2 4 6 8]


## Vector,Matrix,Tensor

In [15]:
Vector=np.array([1,2,3,4])
print("Vector: ",Vector)
Array=np.array([[1,2,3],[4,5,6]])
print("Vector: ",Array)
# Tensor:multidimensional array
Tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 
print("Tensor: ",Tensor)

Vector:  [1 2 3 4]
Vector:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties


In [18]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape of array:",arr.shape)
print("Dimension of array:",arr.ndim)
print("Size of array:",arr.size)
print("Dtype of array:",arr.dtype)

# arr=np.array([[1,2,3],[4,5,True]])
# print("Shape of array:",arr.shape)
# print("Dimension of array:",arr.ndim)
# print("Size of array:",arr.size)
# print("Dtype of array:",arr.dtype)

# arr=np.array([[1,2,3],[4,5,6.9]])
# print("Shape of array:",arr.shape)
# print("Dimension of array:",arr.ndim)
# print("Size of array:",arr.size)
# print("Dtype of array:",arr.dtype)

# arr=np.array([[1,2,3],[4,5,"6"]])
# print("Shape of array:",arr.shape)
# print("Dimension of array:",arr.ndim)
# print("Size of array:",arr.size)
# print("Dtype of array:",arr.dtype)

Shape of array: (2, 3)
Dimension of array: 2
Size of array: 6
Dtype of array: int64


## Array reshaping


In [24]:
Test=np.arange(12)
print("An array: ",Test)
Reshaped=Test.reshape((3,4))
print("Reshaped array: ",Reshaped)

# ravel(): Returns a view of the original array if possible (does not create a new array unless necessary).
# flatten(): Always returns a copy of the original array.
# ravel() is more memory-efficient because it avoids creating a new array when possible.
# flatten() requires extra memory as it always returns a new copy.
# Since ravel() returns a view (when possible), modifying the returned array may change the original array.
# flatten() returns a copy, so modifications to the new array do not affect the original
Flattened=Reshaped.flatten()
print("flattened array: ",Flattened)
raveled=Reshaped.ravel()
print("raveled array: ",raveled)


Transpose=Reshaped.T
print("transpose array: ",Transpose)



An array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
