## Numpy Array Operations.....
numpy arrays are immutable

In [1]:
import numpy as np


## Indexing And Slicing

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3],arr[-6:-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8 [5 6 7]


In [7]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("A particular index: ",arr_2d[1,2])
print("entire row: ",arr_2d[2])
print("entire column: ",arr_2d[:,2])



A particular index:  7
entire row:  [ 9 10 11 12]
entire column:  [ 3  7 11]


## Sorting

In [10]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

unsorted_arr_2d=np.array([[1,7,3],[4,6,2],[5,9,8]])
print("Sorting of 2D array by column: ",np.sort(unsorted_arr_2d,axis=0))
print("Sorting of 2D array by row: ",np.sort(unsorted_arr_2d,axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorting of 2D array by column:  [[1 6 2]
 [4 7 3]
 [5 9 8]]
Sorting of 2D array by row:  [[1 3 7]
 [2 4 6]
 [5 8 9]]


## Filter

In [16]:
numbers=np.array([3, 1, 4, 1, 5, 9, 2, 6])
even_numbers=numbers[numbers %2==0]
print("Even numbers: ",even_numbers)


Even numbers:  [4 2 6]


## Filter with mask


In [17]:
mask=numbers %2 !=0
print("Odd numbers by mask: ",numbers[mask])

Odd numbers by mask:  [3 1 1 5 9]


## Fancy indexing vs np.where()

In [20]:
indices=[1,4,2]
print("Fancy indexing: ",numbers[indices])
np_where=np.where(numbers<3)
print("Np where: ",numbers[np_where])

Fancy indexing:  [1 5 4]
Np where:  [1 1 2]


In [24]:
numbers1=np.arange(11)
condition_array=np.where(numbers1>5,numbers1*4,numbers1)
print(condition_array)
# if(numbers1>5):
#     numbers1*4
# else:
#     numbers1

condition_array1=np.where(numbers1>4,"true","false")
print(condition_array1)
# if(numbers1>4):
#     print("true")
# else:
#     print("false")

[ 0  1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true' 'true']


## Adding and Removing data

In [42]:
arr1=np.arange(4)
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print("Combined array: ",combined)

arr3=np.append(arr1,[6])
print(arr3)

arr4=np.insert(arr1,1,10)
print(arr4)

arr5=np.insert(arr1,1,[5,6,7,8],axis=0)
print(arr5)


new_arr = np.delete(arr1, 2)  # Remove element at index 2
print(new_arr)  

arr2D = np.array([[1, 2], [3, 4], [5, 6]])
new_arr2D = np.delete(arr2D, 1, axis=0)  # Remove second row
print(new_arr2D)
# Output:
# [[1 2]
#  [5 6]]



Combined array:  [0 1 2 3 4 5 6]
[0 1 2 3 6]
[ 0 10  1  2  3]
[0 5 6 7 8 1 2 3]
[0 1 3]
[[1 2]
 [5 6]]


## Array compatibility


In [28]:
a=np.array([1,2,3])
b=np.array([4,5,6,10])
c=np.array([7,8,9])

print("Compatibility check: ",a.shape==b.shape)


Compatibility check:  False


## Adding new row or new column

In [31]:
original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])
updated_original_withrow=np.vstack((original,new_row))
print("Updated array with new row: ",updated_original_withrow)

new_column=np.array([[7,8],[9,10]])
updated_original_withcolumn=np.hstack((original,new_column))

print("Updated array with new column: ",updated_original_withcolumn)


Updated array with new row:  [[1 2]
 [3 4]
 [5 6]]
Updated array with new column:  [[ 1  2  7  8]
 [ 3  4  9 10]]
